# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.17.3

# Mod Properties
mod_version=0.2.1
maven_group=net.threecrows.drehmal_archipelago
archives_base_name=drehmal_archipelago

# Dependencies
fabric_version=0.92.6+1.20.1
koala_lib_version=ebZZum4Z
archipelago_client_version=0.2.1

# Optional Dependencies
jade_version=drol2x1P
jei_version=wbPLxn0B
rei_version=12.1.785
cloth_config_version=11.1.136
architectury_version=9.2.14
emi_version=VvPw7Vi5