package net.threecrows.drehmal_archipelago.archipelago.locations.advancement;

import static net.threecrows.drehmal_archipelago.archipelago.locations.APLocations.*;

import net.minecraft.util.Identifier;
import net.threecrows.drehmal_archipelago.APMod;

public class VanillaAdvancements {
    public static void addVanillaAdvancements() {
        // Drehmal Advancements
        advancement(new Identifier("drehmal/all_effects"));
        advancement(new Identifier("drehmal/all_potions"));
        advancement(new Identifier("drehmal/arbalistic"));
        advancement(new Identifier("drehmal/axolotl_in_a_bucket"));
        advancement(new Identifier("drehmal/balanced_diet"));
        advancement(new Identifier("drehmal/bred_all_animals"));
        advancement(new Identifier("drehmal/breed_an_animal"));
        advancement(new Identifier("drehmal/brew_potion"));
        advancement(new Identifier("drehmal/bullseye"));
        advancement(new Identifier("drehmal/complete_catalogue"));
        advancement(new Identifier("drehmal/create_beacon"));
        advancement(new Identifier("drehmal/create_full_beacon"));
        advancement(new Identifier("drehmal/cure_zombie_villager"));
        advancement(new Identifier("drehmal/distract_piglin"));
        advancement(new Identifier("drehmal/enchant_item"));
        advancement(new Identifier("drehmal/fishy_business"));
        advancement(new Identifier("drehmal/get_wither_skull"));
        advancement(new Identifier("drehmal/hero_of_the_village"));
        advancement(new Identifier("drehmal/honey_block_slide"));
        advancement(new Identifier("drehmal/kill_a_mob"));
        advancement(new Identifier("drehmal/kill_all_mobs"));
        advancement(new Identifier("drehmal/kill_axolotl_target"));
        advancement(new Identifier("drehmal/lightning_rod_with_villager_no_fire"));
        advancement(new Identifier("drehmal/mine_diamond"));
        advancement(new Identifier("drehmal/obtain_netherite_hoe"));
        advancement(new Identifier("drehmal/ol_betsy"));
        advancement(new Identifier("drehmal/plant_seed"));
        advancement(new Identifier("drehmal/return_to_sender"));
        advancement(new Identifier("drehmal/ride_a_boat_with_a_goat"));
        advancement(new Identifier("drehmal/safely_harvest_honey"));
        advancement(new Identifier("drehmal/shiny_gear"));
        advancement(new Identifier("drehmal/shoot_arrow"));
        advancement(new Identifier("drehmal/silk_touch_nest"));
        advancement(new Identifier("drehmal/sleep_in_bed"));
        advancement(new Identifier("drehmal/sniper_duel"));
        advancement(new Identifier("drehmal/spyglass_at_dragon"));
        advancement(new Identifier("drehmal/spyglass_at_ghast"));
        advancement(new Identifier("drehmal/spyglass_at_parrot"));
        advancement(new Identifier("drehmal/summon_iron_golem"));
        advancement(new Identifier("drehmal/summon_wither"));
        advancement(new Identifier("drehmal/tactical_fishing"));
        advancement(new Identifier("drehmal/tame_an_animal"));
        advancement(new Identifier("drehmal/totem_of_undying"));
        advancement(new Identifier("drehmal/trade"));
        advancement(new Identifier("drehmal/two_birds_one_arrow"));
        advancement(new Identifier("drehmal/use_scroll"));
        advancement(new Identifier("drehmal/voluntary_exile"));
        advancement(new Identifier("drehmal/walk_on_powder_snow_with_leather_boots"));
        advancement(new Identifier("drehmal/whos_the_pillager_now"));

        // Lo'Dahr Advancements
        advancement(new Identifier("lodahr/all_pseudo"));
        advancement(new Identifier("lodahr/bibicalaccuracy"));
        advancement(new Identifier("lodahr/explore_lodahr"));
        advancement(new Identifier("lodahr/find_all_portals"));
        advancement(new Identifier("lodahr/find_meteor"));
        advancement(new Identifier("lodahr/find_wastes"));
        advancement(new Identifier("lodahr/hitbystruckbytruck"));
        advancement(new Identifier("lodahr/nah_gift"));
        advancement(new Identifier("lodahr/netherite_armor"));
        advancement(new Identifier("lodahr/obtain_ancient_debris"));
        advancement(new Identifier("lodahr/pokemon"));
        advancement(new Identifier("lodahr/silk_touch_kill"));
        advancement(new Identifier("lodahr/suffer"));
        advancement(new Identifier("lodahr/survive_wastes"));
        advancement(new Identifier("lodahr/throw_trident"));
        advancement(new Identifier("lodahr/very_very_frightening"));
        advancement(new Identifier("lodahr/withstand_cold"));

        // Exploration Advancements
        advancement(new Identifier("advancements", "discoveries/aeongale"));
        advancement(new Identifier("advancements", "discoveries/ancel"));
        advancement(new Identifier("advancements", "discoveries/arbiter"));
        advancement_scout(new Identifier("advancements", "discoveries/arena"), new Identifier("advancements", "discoveries/foundry"));
        advancement_scout(new Identifier("advancements", "discoveries/arenawin"), new Identifier("advancements", "discoveries/foundry"));
        advancement(new Identifier("advancements", "discoveries/athrah"));
        advancement(new Identifier("advancements", "discoveries/avsal"));
        advancement(new Identifier("advancements", "discoveries/avsohmvault"));
        advancement(new Identifier("advancements", "discoveries/bastion"));
        advancement(new Identifier("advancements", "discoveries/bernice"));
        advancement(new Identifier("advancements", "discoveries/burntpalace"));
        advancement(new Identifier("advancements", "discoveries/citadel"));
        advancement(new Identifier("advancements", "discoveries/colonnade"));
        advancement(new Identifier("advancements", "discoveries/core_entry"));
        advancement(new Identifier("advancements", "discoveries/dahr"));
        advancement(new Identifier("advancements", "discoveries/desolation"));
        advancement(new Identifier("advancements", "discoveries/drabyel"));
        advancement(new Identifier("advancements", "discoveries/drehua"));
        advancement(new Identifier("advancements", "discoveries/dusps"));
        advancement(new Identifier("advancements", "discoveries/ebonrun"));
        advancement(new Identifier("advancements", "discoveries/firteid"));
        advancement(new Identifier("advancements", "discoveries/foundry"));
        advancement(new Identifier("advancements", "discoveries/gozak"));
        advancement(new Identifier("advancements", "discoveries/greyspire"));
        advancement(new Identifier("advancements", "discoveries/hellcrags"));
        advancement(new Identifier("advancements", "discoveries/highfall"));
        advancement(new Identifier("advancements", "discoveries/homligrave"));
        advancement(new Identifier("advancements", "discoveries/hovadchear"));
        advancement(new Identifier("advancements", "discoveries/ihted"));
        advancement(new Identifier("advancements", "discoveries/inscription_facility"));
        advancement(new Identifier("advancements", "discoveries/insight_altar"));
        advancement(new Identifier("advancements", "discoveries/khive"));
        advancement(new Identifier("advancements", "discoveries/kiln"));
        advancement(new Identifier("advancements", "discoveries/lai"));
        advancement(new Identifier("advancements", "discoveries/library"));
        advancement(new Identifier("advancements", "discoveries/lodahr"));
        advancement(new Identifier("advancements", "discoveries/maehrnvhos"));
        advancement(new Identifier("advancements", "discoveries/magister"));
        advancement(new Identifier("advancements", "discoveries/meat"));
        advancement(new Identifier("advancements", "discoveries/merijool"));
        advancement(new Identifier("advancements", "discoveries/mohta"));
        advancement(new Identifier("advancements", "discoveries/moon"));
        advancement(new Identifier("advancements", "discoveries/mossfield"));
        advancement(new Identifier("advancements", "discoveries/muhsden"));
        advancement(new Identifier("advancements", "discoveries/naharja"));
        advancement(new Identifier("advancements", "discoveries/nahyn"));
        advancement(new Identifier("advancements", "discoveries/nimahj"));
        advancement(new Identifier("advancements", "discoveries/noha"));
        advancement(new Identifier("advancements", "discoveries/port"));
        advancement(new Identifier("advancements", "discoveries/primal_caverns"));
        advancement(new Identifier("advancements", "discoveries/primalsapling"));
        advancement(new Identifier("advancements", "discoveries/raveloth"));
        advancement(new Identifier("advancements", "discoveries/rehntite"));
        advancement(new Identifier("advancements", "discoveries/resupply_depot"));
        advancement(new Identifier("advancements", "discoveries/rihelma"));
        advancement(new Identifier("advancements", "discoveries/ring_facility"));
        advancement(new Identifier("advancements", "discoveries/sahd"));
        advancement(new Identifier("advancements", "discoveries/salanyr"));
        advancement(new Identifier("advancements", "discoveries/salmevir"));
        advancement(new Identifier("advancements", "discoveries/sanctuary"));
        advancement(new Identifier("advancements", "discoveries/sanctum"));
        advancement(new Identifier("advancements", "discoveries/scarstone"));
        advancement(new Identifier("advancements", "discoveries/sepulchral"));
        advancement(new Identifier("advancements", "discoveries/shatterhorn"));
        advancement(new Identifier("advancements", "discoveries/shrine"));
        advancement(new Identifier("advancements", "discoveries/slime"));
        advancement(new Identifier("advancements", "discoveries/starrise"));
        advancement(new Identifier("advancements", "discoveries/storm_heart"));
        advancement(new Identifier("advancements", "discoveries/teirunn"));
        advancement(new Identifier("advancements", "discoveries/temple"));
        advancement(new Identifier("advancements", "discoveries/tharhan"));
        advancement(new Identifier("advancements", "discoveries/tharxax"));
        advancement(new Identifier("advancements", "discoveries/vayniklah"));
        advancement(new Identifier("advancements", "discoveries/well"));
        advancement(new Identifier("advancements", "discoveries/wokonori"));
        advancement(new Identifier("advancements", "discoveries/yavhlixdiscovery"));
        advancement(new Identifier("advancements", "discoveries/ytaj"));
        advancement(new Identifier("advancements", "discoveries/ziggurat"));
    }
}
